(ns unity.component
  (:import [UnityEngine GameObject Component]))

;; http://docs.unity3d.com/ScriptReference/MonoBehaviour.html
(defprotocol IMonoBehaviour
  (Awake [this] "Awake is called when the script instance is being loaded.")
  (FixedUpdate [this] "This function is called every fixed framerate frame, if the MonoBehaviour is enabled.")
  (LateUpdate [this]  "LateUpdate is called every frame, if the Behaviour is enabled.")
  (OnAnimatorIK [this]  "Callback for setting up animation IK (inverse kinematics).")
  (OnAnimatorMove [this]  "Callback for processing animation movements for modifying root motion.")
  (OnApplicationFocus [this]  "Sent to all game objects when the player gets or loses focus.")
  (OnApplicationPause [this]  "Sent to all game objects when the player pauses.")
  (OnApplicationQuit [this] "Sent to all game objects before the application is quit.")
  (OnAudioFilterRead [this] "If OnAudioFilterRead is implemented, Unity will insert a custom filter into the audio DSP chain.")
  (OnBecameInvisible [this] "OnBecameInvisible is called when the renderer is no longer visible by any camera.")
  (OnBecameVisible [this] "OnBecameVisible is called when the renderer became visible by any camera.")
  (OnCollisionEnter [this]  "OnCollisionEnter is called when this collider/rigidbody has begun touching another rigidbody/collider.")
  (OnCollisionEnter2D [this]  "Sent when an incoming collider makes contact with this object's collider (2D physics only).")
  (OnCollisionExit [this] "OnCollisionExit is called when this collider/rigidbody has stopped touching another rigidbody/collider.")
  (OnCollisionExit2D [this] "Sent when a collider on another object stops touching this object's collider (2D physics only).")
  (OnCollisionStay [this] "OnCollisionStay is called once per frame for every collider/rigidbody that is touching rigidbody/collider.")
  (OnCollisionStay2D [this] "Sent each frame where a collider on another object is touching this object's collider (2D physics only).")
  (OnConnectedToServer [this] "Called on the client when you have successfully connected to a server.")
  (OnControllerColliderHit [this] "OnControllerColliderHit is called when the controller hits a collider while performing a Move.")
  (OnDestroy [this] "This function is called when the MonoBehaviour will be destroyed.")
  (OnDisable [this] "This function is called when the behaviour becomes disabled () or inactive.")
  (OnDisconnectedFromServer [this]  "Called on the client when the connection was lost or you disconnected from the server.")
  (OnDrawGizmos [this]  "Implement OnDrawGizmos if you want to draw gizmos that are also pickable and always drawn.")
  (OnDrawGizmosSelected [this]  "Implement this OnDrawGizmosSelected if you want to draw gizmos only if the object is selected.")
  (OnEnable [this]  "This function is called when the object becomes enabled and active.")
  (OnFailedToConnect [this] "Called on the client when a connection attempt fails for some reason.")
  (OnFailedToConnectToMasterServer [this] "Called on clients or servers when there is a problem connecting to the MasterServer.")
  (OnGUI [this] "OnGUI is called for rendering and handling GUI events.")
  (OnJointBreak [this]  "Called when a joint attached to the same game object broke.")
  (OnLevelWasLoaded [this]  "This function is called after a new level was loaded.")
  (OnMasterServerEvent [this] "Called on clients or servers when reporting events from the MasterServer.")
  (OnMouseDown [this] "OnMouseDown is called when the user has pressed the mouse button while over the GUIElement or Collider.")
  (OnMouseDrag [this] "OnMouseDrag is called when the user has clicked on a GUIElement or Collider and is still holding down the mouse.")
  (OnMouseEnter [this]  "OnMouseEnter is called when the mouse entered the GUIElement or Collider.")
  (OnMouseExit [this] "OnMouseExit is called when the mouse is not any longer over the GUIElement or Collider.")
  (OnMouseOver [this] "OnMouseOver is called every frame while the mouse is over the GUIElement or Collider.")
  (OnMouseUp [this] "OnMouseUp is called when the user has released the mouse button.")
  (OnMouseUpAsButton [this] "OnMouseUpAsButton is only called when the mouse is released over the same GUIElement or Collider as it was pressed.")
  (OnNetworkInstantiate [this]  "Called on objects which have been network instantiated with Network.Instantiate.")
  (OnParticleCollision [this] "OnParticleCollision is called when a particle hits a collider.")
  (OnPlayerConnected [this] "Called on the server whenever a new player has successfully connected.")
  (OnPlayerDisconnected [this]  "Called on the server whenever a player disconnected from the server.")
  (OnPostRender [this]  "OnPostRender is called after a camera finished rendering the scene.")
  (OnPreCull [this] "OnPreCull is called before a camera culls the scene.")
  (OnPreRender [this] "OnPreRender is called before a camera starts rendering the scene.")
  (OnRenderImage [this] "OnRenderImage is called after all rendering is complete to render image.")
  (OnRenderObject [this]  "OnRenderObject is called after camera has rendered the scene.")
  (OnSerializeNetworkView [this]  "Used to customize synchronization of variables in a script watched by a network view.")
  (OnServerInitialized [this] "Called on the server whenever a Network.InitializeServer was invoked and has completed.")
  (OnTriggerEnter [this]  "OnTriggerEnter is called when the Collider other enters the trigger.")
  (OnTriggerEnter2D [this]  "Sent when another object enters a trigger collider attached to this object (2D physics only).")
  (OnTriggerExit [this] "OnTriggerExit is called when the Collider other has stopped touching the trigger.")
  (OnTriggerExit2D [this] "Sent when another object leaves a trigger collider attached to this object (2D physics only).")
  (OnTriggerStay [this] "OnTriggerStay is called once per frame for every Collider other that is touching the trigger.")
  (OnTriggerStay2D [this] "Sent each frame where another object is within a trigger collider attached to this object (2D physics only).")
  (OnValidate [this]  "This function is called when the script is loaded or a value is changed in the inspector (Called in the editor only).")
  (OnWillRenderObject [this]  "OnWillRenderObject is called once for each camera if the object is visible.")
  (Reset [this] "Reset to default values.")
  (Start [this] "Start is called on the frame when a script is enabled just before any of the Update methods is called the first time.")
  (Update [this]  "Update is called every frame, if the MonoBehaviour is enabled.")
  )

(defmacro defcomponent [name args & body]
  `(defscript ~name ~args
    IMonoBehaviour
    ~@body))

